exports.inpatients = [
    {
        firstname:`Bagus`,
        middlename: 'Budi',
        lastname: 'Cahyono',
        mobilenumber: '081298782733',
        gender: 'male',
        address1: 'Jl. Kaliurang, Bandung, West-Java',
        address2: 'Jl. Penjaringan, North-Jakarta, DKI-Jakarta',
        state: 'Indonesia',
        city: 'DKI-Jakarta',
        zipcode: '14440',
        birthplace: 'Bandung',
        birthday: '1990-01-08',
        bloodtype: 'B'
    },
    {
        firstname:`Manaf`,
        middlename: 'Abdi',
        lastname: 'Gemilang',
        mobilenumber: '085672839733',
        gender: 'Male',
        address1: 'Jl. Ahmad Yani, Surabaya, East-Java',
        address2: 'Jl. Surabaya, Central-Jakarta, DKI-Jakarta',
        state: 'Indonesia',
        city: 'Surabaya',
        zipcode: '60234',
        birthplace: 'Surabaya',
        birthday: '1992-05-08',
        bloodtype: 'A'
    },
    {
        firstname:`Asiyah`,
        middlename: 'Kumala',
        lastname: 'Dewi',
        mobilenumber: '081363843299',
        gender: 'Female',
        address1: 'Jl. Raya Jatiwaringin, East-Jakarta, DKI-Jakarta',
        address2: 'Jl. Jend.Basuki Rahmat , Jambi, Jambi',
        state: 'Indonesia',
        city: 'DKI-Jakarta',
        zipcode: '17411',
        birthplace: 'Jambi',
        birthday: '1996-09-28',
        bloodtype: 'O'
    },
]

exports.doctors =[
    {
            firstname:`Ridho`,
            middlename: 'Ardhi',
            lastname: 'Syaiful',
            mobilenumber: '081189472745',
            gender: 'Male',
            address1: 'Jl. Margonda, Depok, West-Java',
            address2: 'Jl. Menteng, Central-Jakarta, DKI-Jakarta',
            state: 'Indonesia',
            city: 'DKI-Jakarta',
            zipcode: '10350',
            birthplace: 'Depok',
            birthday: '1970-01-08',
            nik: '1110658114',
            specialization: 'GI-Surgeon',
            certificate: 'GI-Certificate-surgeon',
            datecertification: '2005-05-29' ,
            countpatientnumber:0
        },
        {
            firstname:`Ahmad`,
            middlename: 'Yusuf',
            lastname: 'Dwiangga',
            mobilenumber: '081282745822',
            gender: 'Male',
            address1: 'Jl. Menteng, Central-Jakarta, DKI-Jakarta',
            address2: 'Jl. Pulo Sirih Utama, Bekasi-City, West-Java',
            state: 'Indonesia',
            city: 'DKI-Jakarta',
            zipcode: '10350',
            birthplace: 'Bekasi',
            birthday: '1968-04-28',
            nik: '1090631332',
            specialization: 'Cardiothoracic Surgeons',
            certificate: 'Cardiothoracic-Certificate-surgeon',
            datecertification: '2004-05-25' ,
            countpatientnumber:0
            },
        {
            firstname:`Bella`,
            middlename: 'Fitria',
            lastname: 'Afifah',
            mobilenumber: '081282745822',
            gender: 'Female',
            address1: 'Jl. Menteng, Central-Jakarta, DKI-Jakarta',
            address2: 'Jl. Raya Jatiwaringin, Bekasi-City, West-Java',
            state: 'Indonesia',
            city: 'DKI-Jakarta',
            zipcode: '10350',
            birthplace: 'Bekasi',
            birthday: '1983-07-14',
            nik: '18301928447',
            specialization: 'Neuro Surgeons',
            certificate: 'Neuro-Certificate-surgeon',
            datecertification: '2010-10-17' ,
            countpatientnumber:0
            },
]

